retail: # Profile Name
 target: dev  # This is the *default* environment (or "target") to use
 outputs:
  dev:
    type: bigquery
    method: service-account
    keyfile: /usr/local/airflow/include/gcp/service_account.json
    project: csv-gcp-migration-etl-project
    dataset: retail
    threads: 1
    timeout_seconds: 300
    location: US